# Generated by Django 5.0.2 on 2024-02-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('skills', models.CharField(max_length=400)),
                ('education', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('previous_work', models.CharField(max_length=200)),
            ],
        ),
    ]
